language: node_js
node_js:
  - node
cache: npm
sudo: false
notifications:
  email: false
if: tag IS blank
before_script:
  - ARTIFACT_PATH="./`node ./scripts/version`"
script:
  - vsce package --out $ARTIFACT_PATH
deploy:
  - provider: script
    script: node ./scripts/release.js
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: vsce publish --packagePath $ARTIFACT_PATH --pat $VSCE_TOKEN
    skip_cleanup: true
    on:
      branch: master

env:
  global:
    - secure: IQZ3iWQFiOCGEeGnDjxe8nY7+2bhsDotPw9Fpd/QYCITUuyFhY0UkeM3MagohWxUQDaX+14Tk5GlnGEMwRcWqsn+DO+a0k5cPmqkALNNAcrCKW+Wafmoyh+ewuSEDk9T9BDxKEtuuTYEkE/rnAY9uZ2LAAmYCEg/phfqdNYiWfu7nthqAFKN00Syatg1y/x6pRwnaij296dkRDf5U5CJ49ziPdMgQ40fUBBG2AJF99ONBUZzgY/JBt2O9V49TB4rwczi6GWa8gM2kN+Ndg2wEaL9ZfAMh63AcPXMJqnWFjkes2Es0PkQxqc7JCnO98Tcp5ugt4Ln1FCeEtyuOCgkIUWIBw7NzA+ADiIfnl1p88kH29z+uF+w4WaNvY2B7SUcHjHGygRQ/uzXvd9cjGVnxWs5RkRPW2S2q+ocJs9kirjNP8sBgyp3PlW5yCLPEGNckNfG785hzycMBNAgrB5gvYsFCqSGR3bXHM6M5txOhqZawjgzeAyZdXarQCW1V4ccUiKTa8OEZrE9eYMp6/xS2ndm20unytxcg3g8S6NFN0ILWzel/LeXyQe1QUnW2NY8yZ8UhnwSFM/AvpM/3/BFEMu+oHbojufKlYNswc94+aQK/lEebxd7tET2r5NkkswYHDRldq4Q2BnkbNLtVHOG1Blo97f7tkaAYw/oNDalNJo=
    - secure: h1EybF0LuKDkTAnOQiBEvadW36+Tdmyl0ByiuujYSDeohoAhqLx/OtgYyM1+3IlgWxLWaQkYIuK7FEr5ku1+6FjJ7lY0htRvAG73A3qsCTqBknattmaovQMCmImlTMuZFqw5ESqrlu5Kr4cMyBvFhTUuGHcPfmnqkzLeORNw3BRVSvS/0T9LxydIMyIA6q6zsw/H1TGLHvkXsbg0kGF1HCxZliKFzBRNH3D0n62wS0REU1sC8OQo6Uf3rvrwwtVu61b6YqvANKHjssdRAq4GACtQBBSp2yz6VbqV9FKK3jCipuPFvgA0Pvb4srxyubJI6HkRl8ZOcEvldn7AAHhqgrtjQ0o0bZtSTzLaETmT3h0EnqGzl0sbSw/Poh2s6kr+6dFRCMYqkzBNC7pGYgc6aoB7jB/RLRt+pcGrXH3dJugLTsixXqb+CROOCHqul2xuSCNG0/jeDMOEFMPYySOdz9Qbd26aYSPT5fEXpF7th8oIGMsqVUT7BTDNpwcr33DGOHRfRpHnW8bRz9fKD4tVUlvGMDm6fADy8FqhOdt5k1ph45j9Q+QHicfSqvVxepx8TcYn4q1H5+po1J0w6MAN0WQBcUlu1vbx/iXQ8EcFFw4NMNuNFIlN4hTKyBcRW+a0FAV6XKd17rMZGUu+JsrfYjWmDfHVK2xLgB6/qBvqpSo=
